### ISSUE TITLE
安装软件包报错

### ISSUE THREAD

**Issue by Norton-z** [RflySim/RflyExpCode#15]
使用安装脚本时，安装失败，报错如下：
1.开始安装eclipse软件...
安装完毕.
2.开始安装FlightGear软件...
错误使用 unzip (line 84)
zip 文件 "D:\RFLYExpPspSoftwarePack\4.HILApps\FlightGear 2016.1.2.zip" 无效。
出错 PX4InstallScript

求助怎么解决？？

**Comment by RflySim** [comment]
你好，应该是你iso安装包解压的时候出了问题（或者安装包本身下载出错）。请换个解压软件重新试一下。
