### ISSUE TITLE
Error in Building "AttitudeControl_FLY"

### ISSUE THREAD

**Issue by EL-Wadi** [RflySim/RflyExpCode#28]
I got this error when I tried to build the model "AttitudeControl_FLY" in e5.4 folder
I followed your instructions and replaced the three files (costom_attctrl_e5, CMakeLists, and logger)  by the given files in the folder "PSPfile" .
After that replacement, I got the same error when I tried to compile any other Hill model in your package..
Everything is OK when I returned to the original firmware files (CMakeLists, and logger)
I am using windows 10 with Matlab 2017 and your latest package  (RflySim V2.29 - 2020/07/08), firmware 1.7

![image](https://user-images.githubusercontent.com/68010957/89288908-11609180-d65f-11ea-8205-c291aab29aa1.png)
![image](https://user-images.githubusercontent.com/68010957/89290120-09a1ec80-d661-11ea-8762-406fcdffe497.png)

**Comment by WANGshouming4937** [comment]
You can try to modify the files instead of replacing with the given files.

**Comment by EL-Wadi** [comment]
You have mentioned in your PPT slides to modify "logger.cpp" by adding “add_topic(“costom_attctrl_e5”, 4)” to the bottom line of “add_common_topic()” . There is no thing called add_common_topic(). There is add_default_topic(). Is this what you mean?

![image](https://user-images.githubusercontent.com/68010957/89307098-58f41700-d679-11ea-8858-515141612246.png)

**Comment by WANGshouming4937** [comment]
What you did is right, and you can modify the number as your wish. "add_common_topics()" appears in the older version, and we will correct the problem.
