### ISSUE TITLE
Mission Generation using QGround Control

### ISSUE THREAD

**Issue by EL-Wadi** [RflySim/RflyExpCode#57]
Can we build the controller using your Package and and use the Qground Control to generate the trajectory? How?

**Comment by RflySim** [comment]
First, you should choose "no" in the "(10) Whether to block the actuator outputs" option of installation UI, which will enable all PX4 functions.
Then, you can delete the modules (EKF, attitude controller, position controller, etc) you want to replace with the generated controller in the cmake file, or comment out the uORB subscribe and publish codes in the cpp file of these modules.
In the end, you can use Simulink to subscribe and publish signals to replace these modules.

For your case, you can replace part of the function of the PX4 navigator module (get trajectory and send target position point to mc_pos_control module). 
Basic knowledge of the PX4 code framework is required for the above modification. You can visit http://dev.px4.io

**Comment by EL-Wadi** [comment]
In real flight what modules are disabled in your package? 
Can we use mavros with your package to do hill with Gazebo?
Another question, if I generate a time based trajectory that is function of time, is the time is initiated (i.e. t=0) when the motors are armed or what?
