### ISSUE TITLE
操作系统当前配置无法安装Win10WSL编译环境

### ISSUE THREAD

**Issue by cwgHN** [RflySim/RflyExpCode#68]
安装高级功能体验版的时候出现如下错误：

安装开始！
错误: 本操作系统当前配置无法安装Win10WSL编译环境，请选择其他。
错误: 检查用户输入阶段出错，安装中止

**Comment by RflySim** [comment]
请按照PPT配置好WSL环境，并按里面的步骤检验一下，是否配置正确。

**Comment by cwgHN** [comment]
谢谢！已经解决。需要先安装Ubuntu子系统
