### ISSUE TITLE
Unable to acquire the Hardware ID. Please rerun this installation script.

### ISSUE THREAD

**Issue by OsamaRyees** [RflySim/RflyExpCode#7]
I tried to run PX4InstallScript.p file in matlam console  butb it fail in my PC but work with my friend's laptop. it gives "Unable to acquire the Hardware ID. Please rerun this installation script." I can run the getGUID.exe and get the ID but I can not pass the value to the installer secript in case it fails to acquire it. I tried Matlab 2019a & b also with admin rights

regards

**Comment by RflySim** [comment]
When did you download the installation file? Please try to download the latest package to solve this problem.

**Comment by OsamaRyees** [comment]
maybe 1 month ago, I would try the new release
