### ISSUE TITLE
MATLAB PX4InstallScript.p 无法正确安装

### ISSUE THREAD

**Issue by TIGER010320** [RflySim/RflyExpCode#85]
下载快完成，出现指令码错
![指令馬錯誤](https://user-images.githubusercontent.com/62137346/152675254-31334d1a-ea54-4bbf-9fad-a7df49533a2f.PNG)
误

**Comment by kcx064** [comment]
用户名有空格？

**Comment by RflySim** [comment]
请尝试下载使用最新版本安装包

**Comment by TIGER010320** [comment]
> 請嘗試下載使用最新版本安裝包

我是由邮件索取的连结下载的，应该是最新的

**Comment by TIGER010320** [comment]
> 請嘗試下載使用最新版本安裝包

我後來發現是無法將路徑放到桌面上，但也找不出原因

**Comment by TIGER010320** [comment]
> > 請嘗試下載使用最新版本安裝包
> 
> 我後來發現無法放到桌面的，但也找不出原因
