### ISSUE TITLE
安装完成后运行软件在环，QGC无法连接

### ISSUE THREAD

**Issue by LESLIEWANGer** [RflySim/RflyExpCode#90]
可以成功安装高级体验版，一键运行SITLRun后打开的QGC界面如下：
<img width="950" alt="image" src="https://user-images.githubusercontent.com/51128132/159125549-15a5b382-921d-4356-9ea1-f2ce0f1c6a2a.png">
此时无法运行软件调试
当插入Pixhawk4mini时，运行HITLRun可以正常运行，QGC可以正常获取数据。

**Comment by RflySim** [comment]
有可能你使用的是WSL2，需要切换成WSL1。参考下面PPT的第8页
http://flyeval.com/doc/RflySim%E9%AB%98%E7%BA%A7%E7%89%88_%E7%AC%AC01%E8%AE%B2_%E6%80%BB%E4%BD%93%E4%BB%8B%E7%BB%8D.pdf

**Comment by LESLIEWANGer** [comment]
> 有可能你使用的是WSL2，需要切换成WSL1。参考下面PPT的第8页 http://flyeval.com/doc/RflySim%E9%AB%98%E7%BA%A7%E7%89%88_%E7%AC%AC01%E8%AE%B2_%E6%80%BB%E4%BD%93%E4%BB%8B%E7%BB%8D.pdf

顺利解决，谢谢老师
